# ==============================================================================
# INSTRUÇÕES PARA O WORKSHOP - SIGA OS 2 PASSOS ABAIXO:
# ==============================================================================

# PASSO 1: DAR UM NOME ÚNICO AO SEU SITE
#   - Pressione 'Ctrl+F' para abrir "Localizar e Substituir".
#   - No campo "Localizar", digite: NOME-UNICO-AQUI
#   - No campo "Substituir", digite um nome único para você (ex: pedro-teixeira).
#   - Clique em "Substituir Todos".

# PASSO 2: ALTERAR A SUA MENSAGEM
#   - Encontre a linha que começa com "  index.html:" e altere a mensagem.
#   - Você pode usar tags HTML como <h1> para títulos e <p> para parágrafos!
#   - Localizados nas linhas 33 e 34
# ==============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: rads-teste-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Workshop K8s</title>
      <style>
        body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; background-color: #282c34; color: white;}
        h1 { color: #61dafb; }
      </style>
    </head>
    <body>
      <h1>Bem-vindo ao Workshop de Kubernetes!</h1>
      <p>Esta mensagem foi gerada por AIA!</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rads-teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rads-teste
  template:
    metadata:
      labels:
        app: rads-teste
    spec:
      containers:
      - name: web
        image: nginx:latest # Usando a imagem oficial e estável do NGINX
        ports:
        - containerPort: 80
        volumeMounts: # Monta o nosso arquivo de mensagem dentro do container
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes: # Define o volume usando o nosso ConfigMap
      - name: html-volume
        configMap:
          name: rads-teste-config
---
apiVersion: v1
kind: Service
metadata:
  name: rads-teste-service
spec:
  type: ClusterIP
  selector:
    app: rads-teste
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rads-teste-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /rads-teste
        pathType: Prefix
        backend:
          service:
            name: rads-teste-service
            port:
              number: 80
